name: Installation Help
description: There is an issue with installing or configuring the TubeArchivist Plex Integration Scanner and Agent
title: "[Installation Help]: "

body:
  - type: markdown
    attributes:
      value: |
        This is most likely not the best place to ask for installation help. There is a helpful community on [Discord](https://github.com/tubearchivist/tubearchivist#connect).

  - type: checkboxes
    id: instructions
    attributes:
      label: Installation instructions
      options:
        - label: I'm running the latest version of the TubeArchivist Plex Integration Scanner and Agent. I have read the latest release notes and installation instructions.
          required: true

  - type: input
    id: os
    attributes:
      label: Operating System
      description: On what operating system are you running Plex on?
      placeholder: ex. Linux, Unraid, Synology...
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Your installation or setup question
      placeholder: Describe your issue
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant [Plex logs](https://github.com/tubearchivist/tubearchivist-plex#log-locations). This will be automatically formatted into code, so no need for backticks.
      render: Shell
    validations:
      required: true
